# Generated by Django 3.0.5 on 2020-04-30 03:55

import datetime
import django.core.validators
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(db_column='index', default=0)),
                ('company', models.CharField(db_column='company', max_length=255)),
            ],
            options={
                'db_table': 'company',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('uid', models.CharField(db_column='uid', max_length=128, primary_key=True, serialize=False, unique=True)),
                ('index', models.IntegerField(db_column='index')),
                ('guid', models.CharField(db_column='guid', max_length=100, null=True)),
                ('has_died', models.BooleanField(db_column='has_died', default=False)),
                ('balance', models.CharField(db_column='balance', max_length=20, null=True)),
                ('picture', models.CharField(db_column='picture', max_length=200, null=True)),
                ('age', models.IntegerField(db_column='age', null=True)),
                ('eye_color', models.CharField(db_column='eye_color', max_length=20, null=True)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('gender', models.CharField(db_column='gender', max_length=20, null=True)),
                ('company_id', models.IntegerField(db_column='company_id', default=0)),
                ('email', models.CharField(db_column='email', max_length=200, null=True, unique=True)),
                ('phone', models.CharField(db_column='phone', max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(17), django.core.validators.MaxLengthValidator(20)])),
                ('address', models.CharField(db_column='address', max_length=255, null=True)),
                ('about', models.CharField(db_column='about', max_length=1000, null=True)),
                ('registered', models.DateTimeField(db_column='registered', default=datetime.datetime.utcnow)),
                ('tags', django_mysql.models.JSONField(db_column='tags', default=list)),
                ('friends', django_mysql.models.JSONField(db_column='friends', default=list)),
                ('greeting', models.CharField(db_column='greeting', max_length=200, null=True)),
                ('favouriteFood', django_mysql.models.JSONField(db_column='favouriteFood', default=dict)),
                ('favourite_fruit', django_mysql.models.JSONField(db_column='favourite_fruit', default=list)),
                ('favourite_vegetable', django_mysql.models.JSONField(db_column='favourite_vegetable', default=list)),
            ],
            options={
                'db_table': 'people',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Txnhist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.CharField(db_column='user', max_length=20, null=True)),
                ('method', models.CharField(db_column='method', max_length=20, null=True)),
                ('api', models.CharField(db_column='api', max_length=100, null=True)),
                ('parameter', django_mysql.models.JSONField(db_column='parameter', default=list)),
            ],
            options={
                'db_table': 'txnhist',
                'managed': True,
            },
        ),
    ]
